name: Deployment Workflow to Azure App Service

on:
  workflow_call:
    inputs:
      env:
        required: true
        type: string
      Resource_Group_Name:
        required: true
        type: string
      
jobs:
  Deployment:
    name: Deploy ${{ inputs.env }}
    runs-on: ubuntu-latest
    environment: ${{ inputs.env }}

    steps:
      - name: Checkout Child Repo
        uses: actions/checkout@v4
        with:
          repository: TAYYAB-BUKC/github-actions-dotnet
          token: ${{ secrets.GITHUB_TOKEN }}
          path: ChildRepoContent

      - name: Install stable Azure CLI
        run: |
          sudo apt-get remove -y azure-cli || true
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
          # pin if needed (uncomment below if bug persists)
          # sudo apt-get install -y azure-cli=2.64.0-1~focal
          az version
          
      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Download a Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: github-actions-artifact
          path: final_artifacts/

      - name: Validate Bicep
        run: |
          az deployment group validate \
            --resource-group ${{ inputs.Resource_Group_Name }} \
            --template-file ChildRepoContent/src/GitHubActionsDotNet.Api/Infrastructure/main.bicep \
            --parameters ChildRepoContent/src/GitHubActionsDotNet.Api/Infrastructure/Environments/${{ inputs.env }}.bicepparam \
            --only-show-errors \
            --output json
            
      - name: Run Bicep
        run: |
          az deployment group create \
            --name ${{ inputs.env }}-deployment-${{ github.run_number }} \
            --template-file ChildRepoContent/src/GitHubActionsDotNet.Api/Infrastructure/main.bicep \
            --parameters ChildRepoContent/src/GitHubActionsDotNet.Api/Infrastructure/Environments/${{ inputs.env }}.bicepparam \
            --resource-group ${{ inputs.Resource_Group_Name }} \
            --only-show-errors \
            --output json

            
      # Deploy to Azure Web apps
      - name: 'Deploy to Azure App Service'
        uses: azure/webapps-deploy@v2
        with: 
          app-name: ${{ vars.APP_NAME }} # Replace with your app name
          slot-name: slot
          package: final_artifacts/
      
      - name: 'Slots Swapping'
        run: |
          az webapp deployment slot swap -g ${{ inputs.Resource_Group_Name }} -n ${{ vars.APP_NAME }} --slot slot --target-slot production --verbose 
        
